# Generated by Django 5.2.4 on 2025-09-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_userfeatureflags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do salão/organização', max_length=255)),
                ('slug', models.SlugField(help_text='Identificador único (URL-friendly)', unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL do logo do salão', null=True)),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Cor primária (hex) para branding', max_length=7)),
                ('secondary_color', models.CharField(default='#1F2937', help_text='Cor secundária (hex) para branding', max_length=7)),
                ('timezone', models.CharField(default='Europe/Lisbon', help_text='Timezone do salão', max_length=50)),
                ('currency', models.CharField(default='EUR', help_text='Moeda padrão (ISO 4217)', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='users_tenan_slug_99d161_idx'), models.Index(fields=['is_active'], name='users_tenan_is_acti_405a25_idx')],
            },
        ),
    ]
