# Generated by Django 5.2.4 on 2025-09-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_tenant_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant/salão ao qual o usuário pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.tenant'),
        ),
    ]
