# Generated by Django 5.2.4 on 2025-09-02 17:27

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_feature_flags_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo do salão (PNG, JPG, SVG - max 2MB)', null=True, upload_to='tenant_logos/', validators=[users.validators.validate_logo_image]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL do logo do salão (para compatibilidade)', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#3B82F6', help_text='Cor primária (hex) para branding', max_length=7, validators=[users.validators.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='secondary_color',
            field=models.CharField(default='#1F2937', help_text='Cor secundária (hex) para branding', max_length=7, validators=[users.validators.validate_hex_color]),
        ),
    ]
