# Generated by Django 5.2.4 on 2025-09-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0008_add_logo_upload_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ops_role',
            field=models.CharField(blank=True, choices=[('ops_admin', 'Ops Admin'), ('ops_support', 'Ops Support')], help_text='Role de staff do console Ops (ops_admin ou ops_support)', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['ops_role'], name='users_custo_ops_rol_465634_idx'),
        ),
    ]
