# Generated by Django 5.2.4 on 2025-10-27 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_add_theme_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="comm_auto_renew",
            field=models.BooleanField(
                default=False,
                help_text="Renovação automática de crédito mensal (Standard+)",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="comm_credit_eur",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Crédito atual de comunicações em euros",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="comm_extra_allowed",
            field=models.BooleanField(
                default=True,
                help_text="Permite compra de créditos avulsos de comunicação",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="custom_domain",
            field=models.CharField(
                blank=True,
                help_text="Domínio personalizado configurado",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="custom_domain_enabled",
            field=models.BooleanField(
                default=False, help_text="Habilita domínio personalizado"
            ),
        ),
        migrations.CreateModel(
            name="CommLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Compra"),
                            ("consumption", "Consumo"),
                            ("expiration", "Expiração"),
                            ("refund", "Reembolso"),
                            ("bonus", "Bônus"),
                        ],
                        help_text="Tipo de transação",
                        max_length=20,
                    ),
                ),
                (
                    "amount_eur",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor da transação em euros",
                        max_digits=10,
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Saldo antes da transação",
                        max_digits=10,
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Saldo após a transação",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        help_text="Status da transação",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrição detalhada da transação"
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de referência externa (ex: Stripe PaymentIntent)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data de expiração do crédito (para compras)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que iniciou a transação",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant proprietário do crédito",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comm_ledger",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="users_comml_tenant__f925b0_idx",
                    ),
                    models.Index(
                        fields=["tenant", "transaction_type"],
                        name="users_comml_tenant__c41bad_idx",
                    ),
                    models.Index(
                        fields=["status"], name="users_comml_status_715cdb_idx"
                    ),
                    models.Index(
                        fields=["reference_id"], name="users_comml_referen_f8a780_idx"
                    ),
                ],
            },
        ),
    ]
