# Generated by Django 5.2.4 on 2025-10-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_commledger_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commledger',
            options={'ordering': ['-created_at'], 'verbose_name': 'Credit History', 'verbose_name_plural': 'Credit History'},
        ),
    ]
