# Generated by Django 5.2.4 on 2025-12-04 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_add_tenant_contact_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="feedback_digest_enabled",
            field=models.BooleanField(
                default=False, help_text="Habilita digest de feedback por e-mail"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="feedback_digest_frequency",
            field=models.CharField(
                blank=True,
                default="daily",
                help_text="Frequência do digest (daily/weekly)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="feedback_digest_last_sent",
            field=models.DateTimeField(
                blank=True, help_text="Último envio de digest de feedback", null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="feedback_digest_time",
            field=models.TimeField(
                blank=True,
                default=datetime.time(9, 0),
                help_text="Horário local do tenant para envio do digest",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="feedback_webhook_url",
            field=models.URLField(
                blank=True,
                help_text="URL de webhook para eventos de feedback",
                null=True,
            ),
        ),
    ]
