# Generated by Django 5.2.4 on 2025-12-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_add_language_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="onboarding_status",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Status do onboarding do usuário (ex: {'tour_completed': True})",
            ),
        ),
    ]
