# Generated by Django 5.2.4 on 2025-12-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_customuser_onboarding_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data de cancelamento do tenant (soft delete)",
                null=True,
            ),
        ),
    ]
