# Generated by Django 5.2.4 on 2026-01-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_tenant_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="plan_tier",
            field=models.CharField(
                choices=[("basic", "Basic"), ("standard", "Standard"), ("pro", "Pro")],
                default="basic",
                help_text="Nível do plano contratado",
                max_length=20,
            ),
        ),
    ]
