# Generated by Django 5.2.4 on 2026-01-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_tenant_plan_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeatureflags",
            name="pro_plan",
            field=models.CharField(
                blank=True,
                choices=[("basic", "Basic"), ("standard", "Standard"), ("pro", "Pro")],
                max_length=20,
                null=True,
            ),
        ),
    ]
