# Generated by Django 5.2.4 on 2026-01-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_alter_userfeatureflags_pro_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_founder",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o tenant possui o plano Founder (limitado a 500)",
            ),
        ),
    ]
