# Generated by Django 5.2.4 on 2026-01-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_tenant_is_founder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="push_web_enabled",
            field=models.BooleanField(
                default=True, help_text="Habilita notificações web push"
            ),
        ),
    ]
