# Generated by Django 5.2.4 on 2026-02-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_alter_tenant_plan_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="cancellation_reason",
            field=models.TextField(
                blank=True,
                help_text="Motivo opcional fornecido pelo owner ao cancelar",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data/hora do cancelamento (soft delete)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="reactivation_token",
            field=models.CharField(
                blank=True,
                help_text="Token HMAC para link de reativação seguro",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="scheduled_deletion_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data agendada para hard delete (calculada automaticamente)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("deleted", "Permanently Deleted"),
                ],
                db_index=True,
                default="active",
                help_text="Status da conta do tenant",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["status", "cancelled_at"], name="users_tenan_status_c942cb_idx"
            ),
        ),
    ]
