# Generated by Django 5.2.4 on 2026-02-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_add_tenant_cancellation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="jwt_version",
            field=models.IntegerField(
                default=1,
                help_text="Versão do token JWT. Incrementado para invalidar tokens existentes.",
            ),
        ),
    ]
