# Generated by Django 5.2.4 on 2026-02-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_customuser_jwt_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="pwa_client_enabled",
            field=models.BooleanField(default=True, help_text="Habilita PWA Cliente"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="reports_enabled",
            field=models.BooleanField(
                default=True, help_text="Habilita módulo de relatórios"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="sms_enabled",
            field=models.BooleanField(
                default=True, help_text="Habilita notificações SMS"
            ),
        ),
    ]
