# Generated by Django 5.2.4 on 2026-02-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_alter_tenant_pwa_client_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="comm_auto_renew",
            field=models.BooleanField(
                default=False, help_text="Renovação automática de crédito mensal (Pro+)"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="plan_tier",
            field=models.CharField(
                choices=[("basic", "Basic"), ("pro", "Pro"), ("founder", "Founder")],
                default="basic",
                help_text="Nível do plano contratado",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userfeatureflags",
            name="pro_plan",
            field=models.CharField(
                blank=True,
                choices=[("basic", "Basic"), ("pro", "Pro")],
                max_length=20,
                null=True,
            ),
        ),
    ]
