# Generated by Django 5.2.4 on 2026-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_customuser_birthday_customuser_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="billing_mode",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("promotional", "Promotional")],
                db_index=True,
                default="stripe",
                help_text="Modo de billing do tenant (Stripe ou promocional interno)",
                max_length=20,
            ),
        ),
    ]
