# Generated by Django 5.2.4 on 2026-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0038_tenant_billing_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="promotional_converts_to_plan",
            field=models.CharField(
                choices=[("basic", "Basic"), ("pro", "Pro")],
                default="basic",
                help_text="Plano pago alvo quando a promoção expirar",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="promotional_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data/hora em que o billing promocional expira, se aplicável",
                null=True,
            ),
        ),
    ]
