# Generated by Django 5.2.4 on 2026-05-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_tenant_promotional_transition_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantBusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_hours",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week"],
                "indexes": [
                    models.Index(
                        fields=["tenant"], name="users_tenan_tenant__02f185_idx"
                    ),
                    models.Index(
                        fields=["tenant", "day_of_week"],
                        name="users_tenan_tenant__fe7f12_idx",
                    ),
                ],
                "unique_together": {("tenant", "day_of_week")},
            },
        ),
    ]
