# Generated by Django 5.2.4 on 2026-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_tenantbusinesshours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='comm_auto_renew_last_purchase_at',
            field=models.DateField(blank=True, help_text='Data da última compra automática de crédito (limite de 1x/dia)', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='comm_auto_renew_price_id',
            field=models.CharField(blank=True, help_text='Stripe price_id do pacote de crédito escolhido para a renovação automática', max_length=255, null=True),
        ),
    ]
