# Generated by Django 5.2.4 on 2026-09-04 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0028_saloncustomer_birthday_saloncustomer_photo'),
        ('users', '0042_tenant_comm_auto_renew_consecutive_failures'),
        ('vouchers', '0004_birthdayvoucherconfig_birthdayvoucherlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('prize_description', models.TextField(blank=True, default='')),
                ('prize_voucher_type', models.CharField(choices=[('percent', 'Percentual'), ('fixed', 'Valor fixo'), ('free_service', 'Serviço grátis')], max_length=20)),
                ('prize_value', models.DecimalField(blank=True, decimal_places=2, help_text="Percentual ou valor fixo. Não se aplica a 'free_service'.", max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('drawn', 'Sorteado')], default='draft', max_length=20)),
                ('drawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='raffles', to='core.saloncustomer')),
                ('prize_service', models.ForeignKey(blank=True, help_text="Obrigatório apenas quando prize_voucher_type='free_service'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffles', to='core.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to='users.tenant')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_raffles', to='core.saloncustomer')),
                ('winner_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffle', to='vouchers.clientvoucher')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
