[pytest]
DJANGO_SETTINGS_MODULE = salonix_backend.settings
python_files = tests.py test_*.py *_tests.py
filterwarnings =
    ignore::UserWarning:rest_framework.fields
    ignore:DateTimeField .* received a naive datetime .*:RuntimeWarning
    ignore::django.utils.deprecation.RemovedInDjango60Warning
