# Generated by Django 5.2.4 on 2025-08-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_cancelled_by_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='available', max_length=20),
        ),
    ]
