# Generated by Django 5.2.4 on 2025-09-02 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_completed_paid_status'),
        ('users', '0004_add_tenant_fk_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='professional',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant'], name='core_appoin_tenant__bfcb83_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'client'], name='core_appoin_tenant__5b4316_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'status'], name='core_appoin_tenant__7d622d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'created_at'], name='core_appoin_tenant__e203e4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'service'], name='core_appoin_tenant__456dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'professional'], name='core_appoin_tenant__a89b01_idx'),
        ),
        migrations.AddIndex(
            model_name='professional',
            index=models.Index(fields=['tenant'], name='core_profes_tenant__a2df9e_idx'),
        ),
        migrations.AddIndex(
            model_name='professional',
            index=models.Index(fields=['tenant', 'user'], name='core_profes_tenant__a09d31_idx'),
        ),
        migrations.AddIndex(
            model_name='professional',
            index=models.Index(fields=['tenant', 'is_active'], name='core_profes_tenant__d8c79c_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['tenant'], name='core_schedu_tenant__207f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['tenant', 'professional'], name='core_schedu_tenant__0ff87e_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['tenant', 'start_time'], name='core_schedu_tenant__3de519_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['tenant', 'is_available'], name='core_schedu_tenant__7637dc_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant'], name='core_servic_tenant__62caed_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant', 'user'], name='core_servic_tenant__6a99b0_idx'),
        ),
    ]
