# Generated by Django 5.2.4 on 2025-10-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_users_customuser_email_ci_unique'),
        ('core', '0012_rename_core_appoin_tenant_serie_idx_core_appoin_tenant__4befb2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.TextField(blank=True)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='users.tenant')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='saloncustomer',
            index=models.Index(fields=['tenant'], name='core_customer_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='saloncustomer',
            index=models.Index(fields=['tenant', 'name'], name='core_customer_name_idx'),
        ),
        migrations.AddIndex(
            model_name='saloncustomer',
            index=models.Index(fields=['tenant', 'email'], name='core_customer_email_idx'),
        ),
        migrations.AddIndex(
            model_name='saloncustomer',
            index=models.Index(fields=['tenant', 'phone_number'], name='core_customer_phone_idx'),
        ),
    ]
