# Generated by Django 5.2.4 on 2025-10-15 00:01

from django.db import migrations


def create_default_customers(apps, schema_editor):
    Tenant = apps.get_model('users', 'Tenant')
    SalonCustomer = apps.get_model('core', 'SalonCustomer')

    for tenant in Tenant.objects.all():
        if not SalonCustomer.objects.filter(tenant=tenant).exists():
            SalonCustomer.objects.create(
                tenant=tenant,
                name="Cliente do salão",
                notes="Placeholder gerado automaticamente para compatibilidade com agendamentos antigos.",
                marketing_opt_in=False,
                is_active=True,
            )


def remove_default_customers(apps, schema_editor):
    SalonCustomer = apps.get_model('core', 'SalonCustomer')
    SalonCustomer.objects.filter(
        name="Cliente do salão",
        notes__startswith="Placeholder gerado automaticamente"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_saloncustomer'),
        ('users', '0011_customuser_users_customuser_email_ci_unique'),
    ]

    operations = [
        migrations.RunPython(create_default_customers, remove_default_customers),
    ]
