# Generated by Django 5.2.4 on 2025-10-15 00:02

from django.db import migrations


def assign_customers(apps, schema_editor):
    Appointment = apps.get_model('core', 'Appointment')
    SalonCustomer = apps.get_model('core', 'SalonCustomer')

    placeholders_cache = {}

    for appointment in Appointment.objects.select_related("tenant"):
        tenant = appointment.tenant
        if not tenant:
            continue
        tenant_id = tenant.id
        placeholder = placeholders_cache.get(tenant_id)
        if placeholder is None:
            placeholder = (
                SalonCustomer.objects.filter(tenant=tenant).order_by("id").first()
            )
            if placeholder is None:
                placeholder = SalonCustomer.objects.create(
                    tenant=tenant,
                    name="Cliente do salão",
                    notes="Placeholder gerado automaticamente para compatibilidade com agendamentos antigos.",
                    marketing_opt_in=False,
                    is_active=True,
                )
            placeholders_cache[tenant_id] = placeholder

        if appointment.customer_id:
            continue
        appointment.customer = placeholder
        appointment.save(update_fields=["customer"])


def unassign_customers(apps, schema_editor):
    Appointment = apps.get_model('core', 'Appointment')
    Appointment.objects.update(customer=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_appointment_customer'),
    ]

    operations = [
        migrations.RunPython(assign_customers, unassign_customers),
    ]
