# Generated by Django 5.2.4 on 2025-11-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_fix_staff_professional_consistency"),
        ("users", "0021_add_app_name_and_favicon_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_links",
                        to="core.professional",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_links",
                        to="core.service",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_services",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("professional_id", "service_id"),
                "indexes": [
                    models.Index(fields=["tenant"], name="core_profsvc_tenant_idx"),
                    models.Index(
                        fields=["tenant", "professional"], name="core_profsvc_prof_idx"
                    ),
                    models.Index(
                        fields=["tenant", "service"], name="core_profsvc_service_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "professional", "service"),
                        name="core_profsvc_unique",
                    )
                ],
            },
        ),
    ]
