# Generated by Django 5.2.4 on 2025-11-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_professionalservice"),
        ("users", "0021_add_app_name_and_favicon_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentReservedSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserved_slots",
                        to="core.appointment",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserved_by_appointments",
                        to="core.scheduleslot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_reserved_slots",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("appointment_id", "slot_id"),
                "indexes": [
                    models.Index(fields=["tenant"], name="core_appres_tenant_idx"),
                    models.Index(
                        fields=["tenant", "appointment"], name="core_appres_app_idx"
                    ),
                ],
            },
        ),
    ]
