# Generated by Django 5.2.4 on 2025-11-24 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_appointmentreservedslot"),
        ("users", "0021_add_app_name_and_favicon_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerCommunicationConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("push", "Push"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("transactional", "Transactional"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("consented", "Consented"),
                            ("withdrawn", "Withdrawn"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        null=True,
                        choices=[
                            ("admin", "Admin"),
                            ("self_service", "Self Service"),
                            ("import", "Import"),
                        ],
                        max_length=16,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=256, null=True)),
                ("version", models.CharField(blank=True, max_length=32, null=True)),
                ("locale", models.CharField(blank=True, max_length=16, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="communication_consents",
                        to="core.saloncustomer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_consents",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("customer_id", "channel", "purpose"),
                "indexes": [
                    models.Index(fields=["tenant"], name="core_commconsent_tenant_idx"),
                    models.Index(
                        fields=["tenant", "customer", "channel"],
                        name="core_commconsent_tc_chan_idx",
                    ),
                    models.Index(
                        fields=["tenant", "customer", "purpose"],
                        name="core_commconsent_tc_purp_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="customercommunicationconsent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "customer", "channel", "purpose"),
                name="core_commconsent_unique",
            ),
        ),
    ]
