# Generated by Django 5.2.4 on 2025-12-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_customercommunicationconsent"),
        ("users", "0021_add_app_name_and_favicon_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug", "Bug"),
                            ("suggestion", "Suggestion"),
                            ("praise", "Praise"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("message", models.TextField()),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedbacks",
                        blank=True,
                        null=True,
                        to="core.saloncustomer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "indexes": [
                    models.Index(fields=["tenant"], name="core_feedback_tenant_idx"),
                    models.Index(fields=["tenant", "category"], name="core_feedback_cat_idx"),
                    models.Index(fields=["tenant", "rating"], name="core_feedback_rating_idx"),
                    models.Index(fields=["tenant", "created_at"], name="core_feedback_created_idx"),
                ],
            },
        ),
    ]

