# Generated by Django 5.2.4 on 2026-01-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="custom_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="category",
            field=models.CharField(
                choices=[
                    ("app", "App"),
                    ("support", "Support"),
                    ("pwa", "PWA"),
                    ("praise", "Praise"),
                    ("other", "Other"),
                ],
                max_length=24,
            ),
        ),
    ]
