# Generated by Django 5.2.4 on 2026-01-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_feedback_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="saloncustomer",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
