# Generated by Django 5.2.4 on 2026-04-02 08:17

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_saloncustomer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloncustomer',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saloncustomer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photos/', validators=[users.validators.validate_profile_image]),
        ),
    ]
