# Generated by Django 5.2.4 on 2026-07-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='minimum_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Estoque mínimo desejado. Usado pelo endpoint de alertas (BE-STOCK-04, #467): um item só entra em alerta quando este valor está definido (não nulo) e maior que zero, e a quantidade atual está no mínimo ou abaixo dele.', null=True),
        ),
    ]
