# Generated by Django 5.2.4 on 2025-09-20 18:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('users', '0009_customuser_ops_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLockout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('source', models.CharField(default='auth', max_length=100)),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_lockouts_resolved', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_lockouts', to='users.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_lockouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-locked_at'],
                'indexes': [models.Index(fields=['tenant', 'locked_at'], name='ops_account_tenant__681aca_idx'), models.Index(fields=['resolved_at'], name='ops_account_resolve_30a67c_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpsAlert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('notification_failure', 'Notification Failure'), ('security_incident', 'Security Incident'), ('system', 'System')], max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_alerts', to='notifications.notificationlog')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_alerts_resolved', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_alerts', to='users.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'severity'], name='ops_opsaler_categor_51737a_idx'), models.Index(fields=['resolved_at'], name='ops_opsaler_resolve_2780b7_idx'), models.Index(fields=['created_at'], name='ops_opsaler_created_01a1c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpsSupportAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('resend_notification', 'Resend Notification'), ('clear_lockout', 'Clear Lockout'), ('resolve_alert', 'Resolve Alert')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_support_actions', to=settings.AUTH_USER_MODEL)),
                ('target_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_support_actions', to='users.tenant')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_support_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='ops_opssupp_action_5e5c88_idx'), models.Index(fields=['actor', 'created_at'], name='ops_opssupp_actor_i_bc6c97_idx')],
            },
        ),
    ]
