# Generated by Django 5.2.4 on 2025-12-23 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="opssupportauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("resend_notification", "Resend Notification"),
                    ("clear_lockout", "Clear Lockout"),
                    ("resolve_alert", "Resolve Alert"),
                    ("update_setting", "Update Setting"),
                    ("update_template", "Update Template"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="OpsGlobalSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Chave única da configuração",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("value", models.TextField(help_text="Valor da configuração")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "Texto"),
                            ("boolean", "Booleano"),
                            ("integer", "Inteiro"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descrição para o admin"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Se visível para endpoints públicos"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ops_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpsNotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único do template (ex: PWA_INVITE)",
                        max_length=100,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "E-mail"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("push", "Push Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Assunto (apenas e-mail/push)",
                        max_length=255,
                    ),
                ),
                ("body_text", models.TextField(help_text="Corpo em texto puro")),
                (
                    "body_html",
                    models.TextField(
                        blank=True, help_text="Corpo em HTML (apenas e-mail)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("code", "channel")},
            },
        ),
    ]
