# Generated by Django 5.2.4 on 2025-12-23 16:13

from django.db import migrations


def seed_notification_templates(apps, schema_editor):
    OpsNotificationTemplate = apps.get_model("ops", "OpsNotificationTemplate")

    # 1. PWA_INVITE
    pwa_invite_text = (
        "Olá,\n\n"
        "Para acessar sua área de cliente, utilize o link abaixo:\n\n"
        "{{ link }}\n\n"
        "Se você não solicitou este acesso, ignore esta mensagem.\n"
    )
    pwa_invite_html = (
        '<div style="font-family: Arial, sans-serif;">\n'
        "  <p>Olá,</p>\n"
        "  <p>Para acessar sua área de cliente, utilize o link abaixo:</p>\n"
        '  <p><a href="{{ link }}" style="background:#2563eb;color:#fff;padding:10px 14px;border-radius:6px;text-decoration:none">Acessar</a></p>\n'
        "  <p>Se você não solicitou este acesso, ignore esta mensagem.</p>\n"
        "</div>"
    )

    OpsNotificationTemplate.objects.get_or_create(
        code="PWA_INVITE",
        channel="email",
        defaults={
            "subject": "Seu acesso ao TimelyOne",
            "body_text": pwa_invite_text,
            "body_html": pwa_invite_html,
            "is_active": True,
        },
    )

    # 2. APPOINTMENT_CONFIRMATION
    # Original used %(client_name)s style formatting, converting to {{ client_name }} for Jinja2/Liquid style which is more standard for templates
    # or keep as python format if we plan to use python format.
    # Given the frontend showed {{ variable }}, I will convert to {{ variable }}.

    appt_conf_text = (
        "Olá {{ client_name }},\n\n"
        'Seu agendamento para o serviço "{{ service_name }}" foi confirmado com sucesso!\n\n'
        "📅 Data e hora: {{ formatted_date }}\n\n"
        "Caso precise remarcar ou cancelar, entre em contato conosco com antecedência.\n\n"
        "Obrigado por escolher {{ salon_name }}! 💈"
    )

    OpsNotificationTemplate.objects.get_or_create(
        code="APPOINTMENT_CONFIRMATION",
        channel="email",
        defaults={
            "subject": "Confirmação do seu agendamento",
            "body_text": appt_conf_text,
            "body_html": "",  # No HTML version found in code, defaulting to empty or same as text wrapped in <p>
            "is_active": True,
        },
    )

    # 3. APPOINTMENT_CANCELLATION
    appt_cancel_text = (
        "Olá {{ client_name }},\n\n"
        'O seu agendamento para o serviço "{{ service_name }}", marcado para {{ formatted_date }}, foi cancelado com sucesso.'
    )

    OpsNotificationTemplate.objects.get_or_create(
        code="APPOINTMENT_CANCELLATION",
        channel="email",
        defaults={
            "subject": "Cancelamento de agendamento",
            "body_text": appt_cancel_text,
            "body_html": "",
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0002_alter_opssupportauditlog_action_opsglobalsetting_and_more"),
    ]

    operations = [
        migrations.RunPython(
            seed_notification_templates, reverse_code=migrations.RunPython.noop
        ),
    ]
