# Generated by Django 5.2.4 on 2026-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0004_alter_opssupportauditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opssupportauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("resend_notification", "Resend Notification"),
                    ("clear_lockout", "Clear Lockout"),
                    ("resolve_alert", "Resolve Alert"),
                    ("update_plan", "Update Plan"),
                    ("update_setting", "Update Setting"),
                    ("update_template", "Update Template"),
                    ("create_ops_user", "Create Ops User"),
                    ("update_ops_user", "Update Ops User"),
                    ("delete_ops_user", "Delete Ops User"),
                ],
                max_length=40,
            ),
        ),
    ]
