# Generated by Django 5.2.4 on 2026-07-31 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0028_saloncustomer_birthday_saloncustomer_photo'),
        ('users', '0041_comm_auto_renew_package_and_last_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Único por tenant. Gerado automaticamente se omitido.', max_length=32)),
                ('type', models.CharField(choices=[('percent', 'Percentual'), ('fixed', 'Valor fixo'), ('free_service', 'Serviço grátis')], max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text="Percentual ou valor fixo. Não se aplica a 'free_service'.", max_digits=10, null=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, help_text="Obrigatório apenas para vouchers do tipo 'free_service'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='core.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='users.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'code'], name='voucher_tenant_code_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='voucher_unique_tenant_code')],
            },
        ),
    ]
