# Generated by Django 5.2.4 on 2026-07-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_saloncustomer_birthday_saloncustomer_photo'),
        ('users', '0041_comm_auto_renew_package_and_last_purchase'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='core.saloncustomer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_vouchers', to='users.tenant')),
                ('used_in_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_used', to='core.appointment')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_vouchers', to='vouchers.voucher')),
            ],
            options={
                'ordering': ('-assigned_at',),
                'indexes': [models.Index(fields=['tenant', 'client'], name='clientvoucher_tenant_cli_idx')],
                'constraints': [models.UniqueConstraint(fields=('voucher', 'client'), name='client_voucher_unique_voucher_client')],
            },
        ),
    ]
