# Generated by Django 5.2.4 on 2026-08-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_saloncustomer_birthday_saloncustomer_photo"),
        ("users", "0041_comm_auto_renew_package_and_last_purchase"),
        ("vouchers", "0003_clientvoucher_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthdayVoucherConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percentual"),
                            ("fixed", "Valor fixo"),
                            ("free_service", "Serviço grátis"),
                        ],
                        default="percent",
                        max_length=20,
                    ),
                ),
                (
                    "voucher_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=10,
                        help_text="Percentual ou valor fixo. Não se aplica a 'free_service'.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "validity_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Validade (em dias, a partir da geração) do voucher de aniversário criado.",
                    ),
                ),
                (
                    "is_selected",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Template usado pelo job de envio automático de "
                            "vouchers de aniversário. No máximo 1 por tenant "
                            "pode estar selecionado — nenhum selecionado "
                            "equivale à feature desligada."
                        ),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obrigatório apenas quando voucher_type='free_service'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="birthday_voucher_configs",
                        to="core.service",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birthday_voucher_configs",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BirthdayVoucherLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birthday_voucher_logs",
                        to="core.saloncustomer",
                    ),
                ),
                (
                    "client_voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="birthday_log_entries",
                        to="vouchers.clientvoucher",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birthday_voucher_logs",
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "sent_date"],
                        name="birthday_log_tenant_date_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "client", "sent_date"),
                        name="birthday_voucher_log_unique_tenant_client_date",
                    )
                ],
            },
        ),
    ]
