# Generated by Django 5.2.4 on 2026-07-30 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0041_comm_auto_renew_package_and_last_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('announcement_type', models.CharField(choices=[('maintenance', 'Manutenção'), ('incident', 'Incidente'), ('fix', 'Correção'), ('feature', 'Novidade'), ('general', 'Geral')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=10)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Início da janela de exibição do comunicado.')),
                ('expire_at', models.DateTimeField(blank=True, help_text='Fim da janela de exibição. Vazio = sem data de expiração.', null=True)),
                ('audience_scope', models.CharField(choices=[('all_tenants', 'Todos os tenants'), ('specific_tenants', 'Tenants específicos'), ('specific_plans', 'Planos específicos')], default='all_tenants', help_text='Como o público-alvo é determinado.', max_length=20)),
                ('target_plans', models.JSONField(blank=True, default=list, help_text="Lista de plan_tier (ex.: ['basic', 'founder']) alvo quando audience_scope=specific_plans.")),
                ('environments', models.JSONField(blank=True, default=list, help_text='Ambientes (dev/uat/prod) onde o comunicado aparece. Vazio = todos.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_announcements_created', to=settings.AUTH_USER_MODEL)),
                ('tenants', models.ManyToManyField(blank=True, help_text='Tenants alvo quando audience_scope=specific_tenants.', related_name='platform_announcements', to='users.tenant')),
            ],
            options={
                'ordering': ('-publish_at', '-created_at'),
                'indexes': [models.Index(fields=['status', 'publish_at'], name='pc_status_publish_idx'), models.Index(fields=['audience_scope'], name='pc_audience_scope_idx')],
            },
        ),
    ]
