# Generated by Django 5.2.4 on 2026-07-30 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_comms', '0001_initial'),
        ('users', '0041_comm_auto_renew_package_and_last_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnnouncementReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('delivered', 'Entregue'), ('read', 'Lido'), ('dismissed', 'Dispensado')], db_index=True, default='delivered', max_length=10)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='platform_comms.platformannouncement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_announcement_receipts', to='users.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_announcement_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='pc_receipt_user_status_idx'), models.Index(fields=['tenant'], name='pc_receipt_tenant_idx')],
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user'), name='pc_receipt_unique_announcement_user')],
            },
        ),
    ]
