# Generated by Django 5.2.4 on 2026-02-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationdevice",
            name="app_version",
            field=models.CharField(
                blank=True,
                help_text="Versão do app mobile (ex: 1.2.3)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notificationdevice",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data/hora do último uso bem-sucedido deste token",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notificationdevice",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[("ios", "iOS"), ("android", "Android")],
                help_text="Sistema operacional do dispositivo (iOS/Android)",
                max_length=10,
                null=True,
            ),
        ),
    ]
