# Generated by Django 5.2.4 on 2026-02-27 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_saloncustomer_password"),
        ("notifications", "0004_manual_add_appointment_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                help_text="Agendamento relacionado (se houver)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="core.appointment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Cliente que recebe a notificação (se não for usuário do sistema)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.saloncustomer",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                help_text="Agendamento relacionado (se houver)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_logs",
                to="core.appointment",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Cliente destinatário",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_logs",
                to="core.saloncustomer",
            ),
        ),
    ]
