# Generated by Django 5.2.4 on 2026-07-09 15:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_appointment_notification_customer_and_more'),
        ('users', '0040_tenantbusinesshours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationdevice',
            unique_together={('tenant', 'user', 'device_type', 'token')},
        ),
    ]
