# Generated by Django 5.2.4 on 2026-09-04 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notificationdevice_unique_together'),
        ('users', '0042_tenant_comm_auto_renew_consecutive_failures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Assunto do email', max_length=255)),
                ('body', models.TextField(help_text='Corpo do email (texto)')),
                ('reply_to', models.EmailField(blank=True, help_text='Reply-To escolhido pelo tenant (opcional); o From é sempre timelyone.today', max_length=254, null=True)),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='queued', max_length=10)),
                ('eligible_count', models.PositiveIntegerField(default=0, help_text='Clientes com consentimento de marketing e email')),
                ('skipped_no_consent_count', models.PositiveIntegerField(default=0, help_text='Clientes com email mas sem consentimento ativo (ou com unsubscribe)')),
                ('free_sent_count', models.PositiveIntegerField(default=0, help_text='Envios cobertos pela cota mensal grátis (50/mês)')),
                ('credit_sent_count', models.PositiveIntegerField(default=0, help_text='Envios excedentes cobrados do crédito de comunicação')),
                ('credit_charged_eur', models.DecimalField(decimal_places=2, default=0, help_text='Total cobrado do crédito de comunicação para esta campanha', max_digits=10)),
                ('blocked_credit_count', models.PositiveIntegerField(default=0, help_text='Elegíveis não enviados por falta de crédito de comunicação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff que compôs/disparou a campanha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant que disparou a campanha', on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to='users.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='notificatio_tenant__1f3d69_idx'), models.Index(fields=['tenant', 'status'], name='notificatio_tenant__fea288_idx')],
            },
        ),
    ]
